CREATE TABLE KUNDE (
    kunde_id NUMBER GENERATED by default on null as IDENTITY PRIMARY KEY,
    kunde_alter NUMBER,
    kunde_name VARCHAR(255),
    kunde_land VARCHAR(255)
);

CREATE TABLE VERKAEUFER (
    verkaeufer_id NUMBER GENERATED by default on null as IDENTITY PRIMARY KEY,
    verkaeufer_geburtsdatum DATE,
    verkaeufer_name VARCHAR(255),
    verkaeufer_fachgebiet VARCHAR(255)
);
